<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;
use kartik\widgets\Select2;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\CashflowDetail */
/* @var $form ActiveForm */
?>

<div class="cashflow-detail-form">

    <?php
    $form = ActiveForm::begin([
            'id' => 'CashflowDetail',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]);

    echo Html::hiddenInput('ru', ReturnUrl::getRequestToken());
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute cashflow_id -->
            <?=
            $form->field($model, 'cashflow_id')->textInput()
            ?>

            <!-- attribute flow -->
            <?=
            // generated by fredyns\suite\giiant\crud\providers\core\OptsProvider::activeField
                $form
                ->field($model, 'flow')
                ->dropDownList(
                    \app\models\CashflowDetail::optsflow()
            );
            ?>

            <!-- attribute nominal -->
            <?=
            $form->field($model, 'nominal')->textInput()
            ?>

            <!-- attribute budgetItem_id -->
            <?=
                $form
                ->field($model, 'budgetItem_id')
                ->widget(Select2::classname(),
                    [
                    'initValueText' => ArrayHelper::getValue($model, 'budgetItem.name', '-'),
                    'options' => ['placeholder' => 'mencari mata anggaran ...'],
                    'pluginOptions' => [
                        'minimumInputLength' => 2,
                        'language' => [
                            'errorLoading' => new JsExpression("function () { return 'menunggu hasil...'; }"),
                        ],
                        'ajax' => [
                            'url' => Url::to(['/api/budget-item/list']),
                            'dataType' => 'json',
                            'data' => new JsExpression('function(params) { return {q:params.term}; }')
                        ],
                        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                        'templateResult' => new JsExpression('function(item) { return item.text; }'),
                        'templateSelection' => new JsExpression('function (item) { return item.text; }'),
                    ],
            ]);
            ?>

            <!-- attribute notes -->
            <?=
            $form->field($model, 'notes')->textarea(['rows' => 6])
            ?>
        </p>

        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => Yii::t('app', 'CashflowDetail'),
                    'content' => $this->blocks['main'],
                    'active' => true,
                ],
            ],
        ]);
        ?>

        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> '.
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-'.$model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

