<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;

/* @var $this yii\web\View */
/* @var $model app\models\CashflowDetail */
/* @var $form ActiveForm */
?>

<div class="cashflow-detail-form">

    <?php
    $form = ActiveForm::begin([
        'id' => 'CashflowDetail',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]);
    
    echo Html::hiddenInput('ru', ReturnUrl::getRequestToken());
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute cashflow_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'cashflow_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Cashflow::find()->all(), 'id', 'id'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['cashflow_id'])),
                ]
            );
            ?>

            <!-- attribute flow -->
            <?=
            // generated by fredyns\suite\giiant\crud\providers\core\OptsProvider::activeField
            $form
                ->field($model, 'flow')
                ->dropDownList(
                    \app\models\CashflowDetail::optsflow()
                );
            ?>

            <!-- attribute nominal -->
            <?=
            $form->field($model, 'nominal')->textInput()
            ?>

            <!-- attribute budgetItem_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'budgetItem_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\BudgetItem::find()->all(), 'id', 'id'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['budgetItem_id'])),
                ]
            );
            ?>

            <!-- attribute monthlyBudgetItem_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'monthlyBudgetItem_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\MonthlyBudgetItem::find()->all(), 'id', 'id'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['monthlyBudgetItem_id'])),
                ]
            );
            ?>

            <!-- attribute notes -->
            <?=
            $form->field($model, 'notes')->textarea(['rows' => 6])
            ?>
        </p>

        <?php $this->endBlock(); ?>
        
        <?=
        Tabs::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label'   => Yii::t('app', 'CashflowDetail'),
                    'content' => $this->blocks['main'],
                    'active'  => true,
                ],
            ],
        ]);
        ?>

        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

