<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;

/* @var $this yii\web\View */
/* @var $model app\models\Cashflow */
/* @var $form ActiveForm */
?>

<div class="cashflow-form">

    <?php
    $form = ActiveForm::begin([
        'id' => 'Cashflow',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]);
    
    echo Html::hiddenInput('ru', ReturnUrl::getRequestToken());
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute cashflowType_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'cashflowType_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\CashflowType::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['cashflowType_id'])),
                ]
            );
            ?>

            <!-- attribute number -->
            <?=
            $form->field($model, 'number')->textInput(['maxlength' => true])
            ?>

            <!-- attribute date -->
            <?=
            // generated by fredyns\suite\giiant\crud\providers\extensions\DateProvider::activeField
            $form
                ->field($model, 'date')
                // TODO: must configured properly together with model
                //->widget(\yii\jui\DatePicker::classname(),
                //    [
                //        'dateFormat' => 'yyyy-MM-dd',
                //    ])
            ?>

            <!-- attribute account_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'account_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Account::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['account_id'])),
                ]
            );
            ?>

            <!-- attribute approved_at -->
            <?=
            $form->field($model, 'approved_at')->textInput()
            ?>

            <!-- attribute approved_by -->
            <?=
            $form->field($model, 'approved_by')->textInput()
            ?>

            <!-- attribute approval -->
            <?=
            // generated by fredyns\suite\giiant\crud\providers\core\OptsProvider::activeField
            $form
                ->field($model, 'approval')
                ->dropDownList(
                    \app\models\Cashflow::optsapproval()
                );
            ?>

            <!-- attribute notes -->
            <?=
            $form->field($model, 'notes')->textarea(['rows' => 6])
            ?>
        </p>

        <?php $this->endBlock(); ?>
        
        <?=
        Tabs::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label'   => Yii::t('app', 'Cashflow'),
                    'content' => $this->blocks['main'],
                    'active'  => true,
                ],
            ],
        ]);
        ?>

        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

