<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;
use kartik\widgets\Select2;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\Cashflow */
/* @var $form ActiveForm */
?>

<div class="cashflow-form">

    <?php
    $form = ActiveForm::begin([
            'id' => 'Cashflow',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]);

    echo Html::hiddenInput('ru', ReturnUrl::getRequestToken());
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute cashflowType_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'cashflowType_id')->dropDownList(
                \app\models\CashflowType::options(),
                [
                'prompt' => 'Select',
                'disabled' => (isset($relAttributes) && isset($relAttributes['cashflowType_id'])),
                ]
            );
            ?>

            <!-- attribute number -->
            <?=
            $form->field($model, 'number')->textInput(['maxlength' => true])
            ?>

            <!-- attribute date -->
            <?=
            // generated by fredyns\suite\giiant\crud\providers\extensions\DateProvider::activeField
                $form
                ->field($model, 'date')
                // TODO: must configured properly together with model
                ->widget(\yii\jui\DatePicker::classname(),
                    [
                    'dateFormat' => 'yyyy-MM-dd',
                ])
            ?>

            <!-- attribute account_id -->
            <?=
                $form
                ->field($model, 'account_id')
                ->widget(Select2::classname(),
                    [
                    'initValueText' => ArrayHelper::getValue($model, 'account.name', '-'),
                    'options' => ['placeholder' => 'mencari akun ...'],
                    'pluginOptions' => [
                        'minimumInputLength' => 2,
                        'language' => [
                            'errorLoading' => new JsExpression("function () { return 'menunggu hasil...'; }"),
                        ],
                        'ajax' => [
                            'url' => Url::to(['/api/account/list']),
                            'dataType' => 'json',
                            'data' => new JsExpression('function(params) { return {q:params.term}; }')
                        ],
                        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                        'templateResult' => new JsExpression('function(item) { return item.text; }'),
                        'templateSelection' => new JsExpression('function (item) { return item.text; }'),
                    ],
            ]);
            ?>

            <!-- attribute notes -->
            <?=
            $form->field($model, 'notes')->textarea(['rows' => 6])
            ?>
        </p>

        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => Yii::t('app', 'Cashflow'),
                    'content' => $this->blocks['main'],
                    'active' => true,
                ],
            ],
        ]);
        ?>

        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> '.
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-'.$model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

