<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "account".
 *
 * @property integer $id
 * @property integer $owner_uid
 * @property string $number
 * @property string $name
 * @property string $currency
 * @property string $accountStatus
 *
 * @property \app\models\Cashflow[] $cashflows
 * @property string $aliasModel
 */
abstract class Account extends \yii\db\ActiveRecord
{
    
    /**
     * ENUM field values
     */
    const ACCOUNTSTATUS_ACTIVE = 'active';
    const ACCOUNTSTATUS_SUSPENDED = 'suspended';

    var $enum_labels = false;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'account';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['owner_uid', 'number', 'name', 'currency'], 'required'],
            [['owner_uid'], 'integer'],
            [['accountStatus'], 'string'],
            [['number'], 'string', 'max' => 32],
            [['name'], 'string', 'max' => 255],
            [['currency'], 'string', 'max' => 8],
            ['accountStatus', 'in', 'range' => [
                    self::ACCOUNTSTATUS_ACTIVE,
                    self::ACCOUNTSTATUS_SUSPENDED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'owner_uid' => 'Owner Uid',
            'number' => 'Number',
            'name' => 'Name',
            'currency' => 'Currency',
            'accountStatus' => 'Account Status',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashflows()
    {
        return $this->hasMany(\app\models\Cashflow::className(), ['account_id' => 'id']);
    }
                
    /**
     * get column accountStatus enum value label
     * @param string $value
     * @return string
     */
    public static function getAccountStatusValueLabel($value)
    {
        $labels = self::optsAccountStatus();

        if(isset($labels[$value])) {
            return $labels[$value];
        }

        return $value;
    }

    /**
     * column accountStatus ENUM value labels
     * @return array
     */
    public static function optsAccountStatus()
    {
        return [
            self::ACCOUNTSTATUS_ACTIVE => self::ACCOUNTSTATUS_ACTIVE,
            self::ACCOUNTSTATUS_SUSPENDED => self::ACCOUNTSTATUS_SUSPENDED,
        ];
    }
    
}
