<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "account".
 *
 * @property integer $id
 * @property string $cif
 * @property string $number
 * @property string $name
 * @property string $currency
 * @property string $accountStatus
 * @property string $recordStatus
 * @property integer $deleted_at
 * @property integer $deleted_by
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Cashflow[] $cashflows
 * @property string $aliasModel
 */
abstract class Account extends \yii\db\ActiveRecord
{
    
    /**
     * ENUM field values
     */
    const ACCOUNTSTATUS_ACTIVE = 'active';
    const ACCOUNTSTATUS_SUSPENDED = 'suspended';
    const RECORDSTATUS_ACTIVE = 'active';
    const RECORDSTATUS_DELETED = 'deleted';

    var $enum_labels = false;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'account';
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cif', 'number', 'name', 'currency'], 'required'],
            [['accountStatus', 'recordStatus'], 'string'],
            [['deleted_at', 'deleted_by'], 'integer'],
            [['cif', 'number'], 'string', 'max' => 32],
            [['name'], 'string', 'max' => 255],
            [['currency'], 'string', 'max' => 8],
            ['accountStatus', 'in', 'range' => [
                    self::ACCOUNTSTATUS_ACTIVE,
                    self::ACCOUNTSTATUS_SUSPENDED,
                ]
            ],
            ['recordStatus', 'in', 'range' => [
                    self::RECORDSTATUS_ACTIVE,
                    self::RECORDSTATUS_DELETED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cif' => 'Cif',
            'number' => 'Number',
            'name' => 'Name',
            'currency' => 'Currency',
            'accountStatus' => 'Account Status',
            'recordStatus' => 'Record Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashflows()
    {
        return $this->hasMany(\app\models\Cashflow::className(), ['account_id' => 'id']);
    }
                
    /**
     * get column accountStatus enum value label
     * @param string $value
     * @return string
     */
    public static function getAccountStatusValueLabel($value)
    {
        $labels = self::optsAccountStatus();

        if(isset($labels[$value])) {
            return $labels[$value];
        }

        return $value;
    }

    /**
     * column accountStatus ENUM value labels
     * @return array
     */
    public static function optsAccountStatus()
    {
        return [
            self::ACCOUNTSTATUS_ACTIVE => self::ACCOUNTSTATUS_ACTIVE,
            self::ACCOUNTSTATUS_SUSPENDED => self::ACCOUNTSTATUS_SUSPENDED,
        ];
    }
    
    /**
     * get column recordStatus enum value label
     * @param string $value
     * @return string
     */
    public static function getRecordStatusValueLabel($value)
    {
        $labels = self::optsRecordStatus();

        if(isset($labels[$value])) {
            return $labels[$value];
        }

        return $value;
    }

    /**
     * column recordStatus ENUM value labels
     * @return array
     */
    public static function optsRecordStatus()
    {
        return [
            self::RECORDSTATUS_ACTIVE => self::RECORDSTATUS_ACTIVE,
            self::RECORDSTATUS_DELETED => self::RECORDSTATUS_DELETED,
        ];
    }
    
}
