<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "budgetItem".
 *
 * @property integer $id
 * @property string $code
 * @property string $description
 *
 * @property \app\models\CashflowDetail[] $cashflowDetails
 * @property \app\models\MonthlyBudgetItem[] $monthlyBudgetItems
 * @property string $aliasModel
 */
abstract class BudgetItem extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'budgetItem';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code'], 'required'],
            [['code'], 'string', 'max' => 64],
            [['description'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Code',
            'description' => 'Description',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashflowDetails()
    {
        return $this->hasMany(\app\models\CashflowDetail::className(), ['budgetItem_id' => 'id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMonthlyBudgetItems()
    {
        return $this->hasMany(\app\models\MonthlyBudgetItem::className(), ['budgetItem_id' => 'id']);
    }
                
}
