<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "cashflowType".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \app\models\Cashflow[] $cashflows
 * @property string $aliasModel
 */
abstract class CashflowType extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cashflowType';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashflows()
    {
        return $this->hasMany(\app\models\Cashflow::className(), ['cashflowType_id' => 'id']);
    }
                
}
