<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "cashflow".
 *
 * @property integer $id
 * @property integer $cashflowType_id
 * @property string $number
 * @property string $date
 * @property string $approval
 * @property integer $account_id
 * @property string $notes
 * @property integer $approved_at
 * @property integer $approved_by
 *
 * @property \app\models\CashflowType $cashflowType
 * @property \app\models\Account $account
 * @property \app\models\CashflowDetail[] $cashflowDetails
 * @property string $aliasModel
 */
abstract class Cashflow extends \yii\db\ActiveRecord
{
    
    /**
     * ENUM field values
     */
    const APPROVAL_PENDING = 'pending';
    const APPROVAL_APPROVED = 'approved';

    var $enum_labels = false;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cashflow';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cashflowType_id', 'number', 'date', 'account_id'], 'required'],
            [['cashflowType_id', 'account_id', 'approved_at', 'approved_by'], 'integer'],
            [['date'], 'safe'],
            [['approval', 'notes'], 'string'],
            [['number'], 'string', 'max' => 32],
            [['cashflowType_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CashflowType::className(), 'targetAttribute' => ['cashflowType_id' => 'id']],
            [['account_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Account::className(), 'targetAttribute' => ['account_id' => 'id']],
            ['approval', 'in', 'range' => [
                    self::APPROVAL_PENDING,
                    self::APPROVAL_APPROVED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cashflowType_id' => 'Cashflow Type',
            'number' => 'Number',
            'date' => 'Date',
            'approval' => 'Approval',
            'account_id' => 'Account',
            'notes' => 'Notes',
            'approved_at' => 'Approved At',
            'approved_by' => 'Approved By',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashflowType()
    {
        return $this->hasOne(\app\models\CashflowType::className(), ['id' => 'cashflowType_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccount()
    {
        return $this->hasOne(\app\models\Account::className(), ['id' => 'account_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashflowDetails()
    {
        return $this->hasMany(\app\models\CashflowDetail::className(), ['cashflow_id' => 'id']);
    }
                
    /**
     * get column approval enum value label
     * @param string $value
     * @return string
     */
    public static function getApprovalValueLabel($value)
    {
        $labels = self::optsApproval();

        if(isset($labels[$value])) {
            return $labels[$value];
        }

        return $value;
    }

    /**
     * column approval ENUM value labels
     * @return array
     */
    public static function optsApproval()
    {
        return [
            self::APPROVAL_PENDING => self::APPROVAL_PENDING,
            self::APPROVAL_APPROVED => self::APPROVAL_APPROVED,
        ];
    }
    
}
