<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "monthly_budgetItem".
 *
 * @property integer $id
 * @property string $year
 * @property integer $month
 * @property integer $budgetItem_id
 * @property double $openBalance
 * @property double $debit
 * @property double $credit
 * @property double $closingBalance
 *
 * @property \app\models\CashflowDetail[] $cashflowDetails
 * @property \app\models\BudgetItem $budgetItem
 * @property string $aliasModel
 */
abstract class MonthlyBudgetItem extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'monthly_budgetItem';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['year', 'month', 'budgetItem_id'], 'required'],
            [['year'], 'safe'],
            [['month', 'budgetItem_id'], 'integer'],
            [['openBalance', 'debit', 'credit', 'closingBalance'], 'number'],
            [['budgetItem_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BudgetItem::className(), 'targetAttribute' => ['budgetItem_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'year' => 'Year',
            'month' => 'Month',
            'budgetItem_id' => 'Budget Item',
            'openBalance' => 'Open Balance',
            'debit' => 'Debit',
            'credit' => 'Credit',
            'closingBalance' => 'Closing Balance',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashflowDetails()
    {
        return $this->hasMany(\app\models\CashflowDetail::className(), ['monthlyBudgetItem_id' => 'id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBudgetItem()
    {
        return $this->hasOne(\app\models\BudgetItem::className(), ['id' => 'budgetItem_id']);
    }
                
}
