<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "uploaded_file".
 *
 * @property string $id
 * @property string $name
 * @property string $filename
 * @property integer $size
 * @property string $type
 *
 * @property \app\models\Profile[] $profiles
 * @property string $aliasModel
 */
abstract class UploadedFile extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'uploaded_file';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['filename'], 'string'],
            [['size'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['type'], 'string', 'max' => 64]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'filename' => 'Filename',
            'size' => 'Size',
            'type' => 'Type',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfiles()
    {
        return $this->hasMany(\app\models\Profile::className(), ['picture_id' => 'id']);
    }
                
}
