<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;

/* @var $this yii\web\View */
/* @var $model app\models\MonthlyBudgetItem */
/* @var $form ActiveForm */
?>

<div class="monthly-budget-item-form">

    <?php
    $form = ActiveForm::begin([
        'id' => 'MonthlyBudgetItem',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]);
    
    echo Html::hiddenInput('ru', ReturnUrl::getRequestToken());
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute year -->
            <?=
            // generated by fredyns\suite\giiant\crud\providers\extensions\DateProvider::activeField
            $form
                ->field($model, 'year')
                // TODO: must configured properly together with model
                //->widget(\yii\jui\DatePicker::classname(),
                //    [
                //        'dateFormat' => 'yyyy-MM-dd',
                //    ])
            ?>

            <!-- attribute month -->
            <?=
            $form->field($model, 'month')->textInput()
            ?>

            <!-- attribute budgetItem_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'budgetItem_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\BudgetItem::find()->all(), 'id', 'id'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['budgetItem_id'])),
                ]
            );
            ?>

            <!-- attribute openBalance -->
            <?=
            $form->field($model, 'openBalance')->textInput()
            ?>

            <!-- attribute debit -->
            <?=
            $form->field($model, 'debit')->textInput()
            ?>

            <!-- attribute credit -->
            <?=
            $form->field($model, 'credit')->textInput()
            ?>

            <!-- attribute closingBalance -->
            <?=
            $form->field($model, 'closingBalance')->textInput()
            ?>
        </p>

        <?php $this->endBlock(); ?>
        
        <?=
        Tabs::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label'   => Yii::t('app', 'MonthlyBudgetItem'),
                    'content' => $this->blocks['main'],
                    'active'  => true,
                ],
            ],
        ]);
        ?>

        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

