<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;
use kartik\widgets\Select2;
use yii\web\JsExpression;
use app\models\MonthlyBudgetItem;

/* @var $this yii\web\View */
/* @var $model app\models\MonthlyBudgetItem */
/* @var $form ActiveForm */
?>

<div class="monthly-budget-item-form">

    <?php
    $form = ActiveForm::begin([
            'id' => 'MonthlyBudgetItem',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]);

    echo Html::hiddenInput('ru', ReturnUrl::getRequestToken());
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute year -->
            <?=
            // generated by fredyns\suite\giiant\crud\providers\extensions\DateProvider::activeField
                $form
                ->field($model, 'year')
            // TODO: must configured properly together with model
            //->widget(\yii\jui\DatePicker::classname(),
            //    [
            //        'dateFormat' => 'yyyy-MM-dd',
            //    ])
            ?>

            <!-- attribute month -->
            <?=
                $form
                ->field($model, 'month')
                ->dropDownList(
                    MonthlyBudgetItem::optsMonth(),
                    [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['month'])),
                    ]
            );
            ?>

            <!-- attribute budgetItem_id -->
            <?=
                $form
                ->field($model, 'budgetItem_id')
                ->widget(Select2::classname(),
                    [
                    'initValueText' => ArrayHelper::getValue($model, 'budgetItem.name', '-'),
                    'options' => ['placeholder' => 'mencari mata anggaran ...'],
                    'pluginOptions' => [
                        'minimumInputLength' => 2,
                        'language' => [
                            'errorLoading' => new JsExpression("function () { return 'menunggu hasil...'; }"),
                        ],
                        'ajax' => [
                            'url' => Url::to(['/api/budget-item/list']),
                            'dataType' => 'json',
                            'data' => new JsExpression('function(params) { return {q:params.term}; }')
                        ],
                        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                        'templateResult' => new JsExpression('function(item) { return item.text; }'),
                        'templateSelection' => new JsExpression('function (item) { return item.text; }'),
                    ],
            ]);
            ?>

            <!-- attribute openBalance -->
            <?=
            $form->field($model, 'openBalance')->textInput()
            ?>

            <!-- attribute debit -->
            <?=
            $form->field($model, 'debit')->textInput()
            ?>

            <!-- attribute credit -->
            <?=
            $form->field($model, 'credit')->textInput()
            ?>

            <!-- attribute closingBalance -->
            <?=
            $form->field($model, 'closingBalance')->textInput()
            ?>
        </p>

        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => Yii::t('app', 'MonthlyBudgetItem'),
                    'content' => $this->blocks['main'],
                    'active' => true,
                ],
            ],
        ]);
        ?>

        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> '.
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-'.$model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

